# QUASIMODO
source "$SCRIPT_DIR/../configs/common.conf"
REPO="https://github.com/s-jobra/QuasimodoSimulator.git"
DIR="$SIMULATORS_DIR/quasimodo"
DEPS=("make" "git" "libmpfr-dev" "autoconf")
PIPDEPS=("invoke")

